### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#168]
**Describe the bug**
When a domain takes a domain, the cron does not put it as canceled. This worked in the past, now we have to put it manually canceled.

**To Reproduce**
Transfer a domain out.

**Comment by wmetge** [comment]
@coriaweb Thanks for bringing this to our attention, we'll take a look at it as soon as possible.

**Comment by maverick85** [comment]
This was reported May 2021.
It's December 2022 and the issue is still present, NOTHING was done. I have opened two bugs in the last 7 days, they have zero interactions. I believe it's time to start reviewing OpenProvider with some brutal honestly because a small business relying on OpenProvider to solve the problems on their code gets screwed, provides a bad service to its customers, and here no one cares. ridiculous.

**Comment by sapillai** [comment]
Hi @coriaweb,

Really sorry for the delay in getting back to you.

We have created a custom function for marking transferred out domains as cancelled. We tested it internally and it is working as expected. We are currently testing it further and plan to include it in the next release. If you are interested to participate in beta testing of the feature, please let me know.

**Comment by coriaweb** [comment]
> Hi @coriaweb,
> 
> Really sorry for the delay in getting back to you.
> 
> We have created a custom function for marking transferred out domains as cancelled. We tested it internally and it is working as expected. We are currently testing it further and plan to include it in the next release. If you are interested to participate in beta testing of the feature, please let me know.

Hello! I have fewer than 50 domains left with you and we continue migrating them out as they expire. What happened with this module is incomprehensible.

I'm sorry, it's already too late.

**Comment by sapillai** [comment]
Hi @coriaweb,

Thank you for your reply and really sorry to hear that you are transferring out domains. 

We released a new version of the WHMCS domain registrar module last week with many improvements and bug fixes. The new version of the module is compatible with PHP 8.1.  You can find the full list of features & improvements and bug fixes [here](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0).

**Comment by maverick85** [comment]
@sapillai 

the bug reported here is still present.
I just had a transfer out and when I consult the domain status it gives

> Registrar Error
> Domain does not exist in Openprovider!

and on the domain details, under `Status` is listed as **ACTIVE** when it should be _Transferred Out_

**Comment by sapillai** [comment]
Hi @maverick85,

> the bug reported here is still present.

Yes, we are aware of it. 

We created a feature for marking transferred out domains as cancelled during domain sync. Our internal testing has shown that it works as intended. We are currently conducting further tests internally and aim to include this feature in the upcoming release.

If you are interested to participate in beta testing of the feature, please let me know. I will add you to the list and will share beta version when it is ready.

**Comment by maverick85** [comment]
@sapillai why cancelled when the domain is transferred out?

Anyway, we're simply reporting bugs we find. There was already an issue for this, so I commented here.

I just don't understand the purpose of communicating on a given issue that there is a new update, when the update does not cover the issue reported and the issue is still present.

Either way, the correct status for domains transferred out by clients is "Transferred Away" not Cancelled. The customer did not cancel the domain, transferred it.

**Comment by sapillai** [comment]
Hi @maverick85,

> I just don't understand the purpose of communicating on a given issue that there is a new update, when the update does not cover the issue reported and the issue is still present.

Apologies if my reply caused confusion. Since this thread didn't had any updates from our side in last couple of years, I wanted to share the update that we have picked this issue and the feature is currently in testing phase ([_...We are currently testing it further and plan to include it in the next release..._](https://github.com/openprovider/Openprovider-WHMCS-domains/issues/168#issuecomment-2145124565)). Also, wanted to know if there is any interest in beta testing the feature when it is available.

> Either way, the correct status for domains transferred out by clients is "Transferred Away" not Cancelled. 

My bad, the status will be "Transferred Away" as you pointed out.
