### ISSUE TITLE
Domain Transfer Status Cron Error: Route does not exist.

### ISSUE THREAD

**Issue by sdmpxs** [openprovider/OP-WHMCS7#56]
**OP 3.0**

When domains are pending transfer, the log is showing the above error for the main system DomainTransferSync cron job. The domains are not updated even though they are active within OpenProvider.

If the domain is set to "Active" manually, the next OpenProvider cron sync shows this error:

`ERRORS: Please check manually the following domains:`

The domain is then listed with the message: "Unexpected data found."

The module log seems to show the correct data in the XML return. Any ideas where I can look to get this fixed.

**Comment by hostingwalk** [comment]
I can confirm this bug.

**Comment by wmetge** [comment]
Thank you for raising this issue. We will let you know when a fix is released.

**Comment by hostingwalk** [comment]
> Thank you for raising this issue. We will let you know when a fix is released.

Any update ?

**Comment by sdmpxs** [comment]
Is there a workaround we can use for this issue? We've now got a number of domains that are pending transfer with no expiry date. Thanks.

**Comment by soberoctober** [comment]
resolved in [v3.1](https://github.com/openprovider/OP-WHMCS7/releases/tag/v3.1)

**Comment by soberoctober** [comment]
@sdmpxs 

> Is there a workaround we can use for this issue? We've now got a number of domains that are pending transfer with no expiry date. Thanks.
Please try updating to version 3.1 and running DomainSync.php script.

**Comment by sdmpxs** [comment]
@soberoctober  Thanks. The issue with "Pending Transfer" domains is still there with V3.1. I have several "Active" domains in Openprovider, but they are still showing as "Pending Transfer" in WHMCS. The only workaround I have found so far is to manually set the expiry date and set the domains as "Active"

**Comment by willdashwood** [comment]
Same here. Just updated to very latest release and run both domainsync.php and modules/registrars/openprovider/cron/DomainSync.php. No errors any more but it doesn't update the status from Pending Transfer to Active on the domains that have completed transfer.

**Comment by soberoctober** [comment]
@sdmpxs @willdashwood 

Does `whmcs.tblDomainSyncOpenprovider` table already contain `last_sync` date from previous runs for those domains?
Try removing rows from the table for the domains that are in Pending Transfer and running the script again.

**Comment by sdmpxs** [comment]
@soberoctober 
There were rows with last_sync as 0000-00-00 00:00:00 for all of the Pending Transfer domains. I deleted the rows, ran the sync and the rows have all reappeared with the same value of 0000-00-00 00:00:00.

**Comment by soberoctober** [comment]
@sdmpxs can you share those domain names?

**Comment by sdmpxs** [comment]
@soberoctober 
Here are two of them:

- stamfordfineart.com 
- flexitrailers.com

If you need more, I can contact you directly with details.

**Comment by willdashwood** [comment]
This seems to be fixed in latest release. Can I just confirm, do we still need a separate cron for modules/registrars/openprovider/cron/DomainSync.php because I just ran crons/domainsync.php and that seemed to update the transfer status for OpenProvider domains.

**Comment by sdmpxs** [comment]
@willdashwood Did you delete the suggested rows from the database or has it just started working for you? We still have "Pending Transfer" domains as before.

**Comment by willdashwood** [comment]
No, didn't touch the database. I just grabbed the latest release this morning. I "watch" the project so get notification when the code has been updated.

**Comment by willdashwood** [comment]
@sdmpxs Hold fire on updating. There's a critical error with DomainSync.php in latest release. Issue #63

**Comment by sdmpxs** [comment]
Ah. I saw that, but it was the same version from the last commit. I re-downloaded to be sure, but I can confirm that I still have "Pending Transfer" domains and I also deleted the DB table rows for them, too. At least you're sorted now, though :-)

**Comment by soberoctober** [comment]
Fixed in 1baba70

**Comment by markholland83** [comment]
> resolved in [v3.1](https://github.com/openprovider/OP-WHMCS7/releases/tag/v3.1)
> 
> **UPD**
> Partially resolved in 3.1.
> Complete fix will be rolled out in 3.3.

We (think) that we are running 3.1 and still have this bug.
How to check which version we are running?

**Comment by soberoctober** [comment]
@markholland83 version number can be found either in the <client></client> filed of the module logs (Utilities > Logs > Module logs) or in `modules/registrars/openprovider/OpenProvider/API/APIConfig.php` file ($moduleVersion field in APIConfig class).

The issues has been completely resolved in version 3.2-beta ([v3.2 branch](https://github.com/openprovider/OP-WHMCS7/tree/v3.2))

**Comment by markholland83** [comment]
Thanks! Good to know where we can find the version number.
When will 3.2 go out of beta? We would very much like to not run BETA :)
